"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { CalendarDays, CalendarOff, Coins, LayoutDashboard, MoreHorizontal, Search, Settings2, ShieldCheck, UsersRound, WalletCards, X, Clock3, Plus, Pencil } from "lucide-react";
import { useState } from "react";
const side=[{href:"/admin",label:"Overview",icon:LayoutDashboard},{href:"/admin/bookings",label:"Bookings",icon:CalendarDays},{href:"/admin/courts",label:"Courts & Hours",icon:Settings2},{href:"/admin/court-blocks",label:"Court Blocks",icon:CalendarOff},{href:"/admin/members",label:"Members",icon:UsersRound},{href:"/admin/wallet",label:"Wallet Adjustments",icon:WalletCards}];
const members=[["BS","Bernard Small","Member","Active","1 hr","650 CC","2"],["AK","Aimee King","Pickle Pro","Active","2 hrs","480 CC","1"],["LM","Liam Meyer","Play & Go","No expiry","—","320 CC","0"],["NK","Nadia Khan","Member","Expiring","0 hrs","910 CC","1"],["SV","Simon Venter","Pickle Pro","Active","1 hr","740 CC","3"]];
function Header({title,desc,action}:{title:string;desc:string;action?:React.ReactNode}){return <div className="page-header" style={{marginBottom:22}}><div><div className="eyebrow">Administrator</div><h1>{title}</h1><p className="subtle" style={{margin:0}}>{desc}</p></div>{action}</div>}
function MemberTable({onManage}:{onManage:(name:string)=>void}){return <div className="table-wrap"><table className="admin-table"><thead><tr><th>Player</th><th>Plan</th><th>Status</th><th>Free hours</th><th>Wallet</th><th>Upcoming</th><th></th></tr></thead><tbody>{members.map(m=><tr key={m[1]}><td><div className="member-cell"><div className="avatar">{m[0]}</div><div><strong style={{display:"block",color:"var(--navy)"}}>{m[1]}</strong><span style={{fontSize:11,color:"var(--muted)"}}>player@clubcourt.co.za</span></div></div></td><td><span className="badge badge-navy">{m[2]}</span></td><td><span className={`badge ${m[3]==="Expiring"?"badge-yellow":"badge-green"}`}>{m[3]}</span></td><td><strong>{m[4]}</strong></td><td>{m[5]}</td><td>{m[6]}</td><td><button className="btn btn-secondary btn-sm" onClick={()=>onManage(m[1])}>Manage</button></td></tr>)}</tbody></table></div>}
export function AdminUI(){
 const pathname=usePathname(); const [managed,setManaged]=useState<string|null>(null);
 const overview=pathname==="/admin";
 return <div className="admin-shell"><aside className="admin-sidebar"><div className="admin-sidebar-label">Admin workspace</div>{side.map(({href,label,icon:Icon})=><Link key={href} href={href} className={`admin-link ${pathname===href?"active":""}`}><Icon size={17}/>{label}</Link>)}</aside><main className="admin-content">
 {overview&&<><Header title="Club Overview" desc="Manage bookings, members, courts, memberships, hours and Club Credits." action={<button className="btn btn-primary"><ShieldCheck size={16}/> View as player</button>}/><div className="stat-grid"><div className="card stat-card"><div className="stat-icon"><CalendarDays size={19}/></div><div className="stat-label">Today’s bookings</div><div className="stat-value">18</div><div className="stat-helper">Across all 6 courts</div></div><div className="card stat-card"><div className="stat-icon"><UsersRound size={19}/></div><div className="stat-label">Active members</div><div className="stat-value">86</div><div className="stat-helper">31 Member · 18 Pickle Pro</div></div><div className="card stat-card"><div className="stat-icon"><Coins size={19}/></div><div className="stat-label">Credits in wallets</div><div className="stat-value">34.8k</div><div className="stat-helper">Simulated balance total</div></div><div className="card stat-card"><div className="stat-icon"><CalendarOff size={19}/></div><div className="stat-label">Court blocks</div><div className="stat-value">3</div><div className="stat-helper">Next 7 days</div></div></div><section className="section card card-pad"><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,marginBottom:16}}><div><h2 style={{marginBottom:4}}>Members</h2><p className="subtle" style={{fontSize:12,margin:0}}>Membership, allowance, wallet and upcoming booking overview.</p></div><Link href="/admin/members" className="btn btn-secondary btn-sm">View all</Link></div><MemberTable onManage={setManaged}/></section></>}
 {pathname==="/admin/bookings"&&<><Header title="Bookings" desc="Filter, inspect, create, edit and cancel court reservations." action={<button className="btn btn-primary"><Plus size={16}/> Create booking</button>}/><section className="card card-pad"><div className="filters"><input className="filter-control" placeholder="Search player or reference"/><select className="filter-control"><option>All courts</option><option>Court 1</option><option>Court 2</option></select><select className="filter-control"><option>All statuses</option><option>Upcoming</option><option>Completed</option><option>Cancelled</option></select></div><div className="table-wrap"><table className="admin-table"><thead><tr><th>Reference</th><th>Player</th><th>Court</th><th>Date & time</th><th>Payment</th><th>Status</th><th></th></tr></thead><tbody>{[["CC-0823-0317","Bernard Small","Court 3","23 Aug · 17:00","Free hour","Upcoming"],["CC-0823-0115","Aimee King","Court 1","23 Aug · 15:00","Club Credits","Upcoming"],["CC-0822-0416","Simon Venter","Court 4","22 Aug · 16:00","Club Credits","Completed"]].map(r=><tr key={r[0]}>{r.slice(0,6).map((c,i)=><td key={i}>{i===5?<span className={`badge ${c==="Upcoming"?"badge-green":"badge-gray"}`}>{c}</span>:c}</td>)}<td><button className="action-menu"><MoreHorizontal size={17}/></button></td></tr>)}</tbody></table></div></section></>}
 {pathname==="/admin/courts"&&<><Header title="Courts & Operating Hours" desc="Manage all six courts, standard prices and the shared club opening schedule." action={<button className="btn btn-primary"><Clock3 size={16}/> Edit hours</button>}/><section className="card card-pad"><div className="courts-grid">{[1,2,3,4,5,6].map(n=><div key={n} className="card court-card" style={{boxShadow:"none"}}><div className="court-card-head"><div><div className="court-name">Court {n}</div><div className="court-meta">{n===3||n===4?"Competition surface":"Premium acrylic"}</div></div><span className={`badge ${n===5?"badge-yellow":"badge-green"}`}>{n===5?"Maintenance":"Open"}</span></div><div className="hours-list"><div className="hours-row"><span>Mon–Sat</span><strong>09:00–19:00</strong></div><div className="hours-row"><span>Sunday</span><strong>15:00–19:00</strong></div><div className="hours-row"><span>Standard price</span><strong>{n===3||n===4?140:120} CC/hr</strong></div></div><button className="btn btn-secondary btn-sm" style={{width:"100%",marginTop:14}}><Pencil size={14}/> Edit court</button></div>)}</div></section></>}
 {pathname==="/admin/court-blocks"&&<><Header title="Court Blocks" desc="Reserve courts for maintenance, club events or private use." action={<button className="btn btn-primary"><Plus size={16}/> Add court block</button>}/><section className="card card-pad"><div className="table-wrap"><table className="admin-table"><thead><tr><th>Court</th><th>Date</th><th>Time</th><th>Type</th><th>Reason</th><th></th></tr></thead><tbody>{[["Court 5","23 Aug 2026","17:00–18:00","Maintenance","Net replacement"],["Court 1–2","30 Aug 2026","15:00–19:00","Event","Club open play"],["Court 6","2 Sep 2026","12:00–14:00","Private use","Coaching session"]].map(r=><tr key={r.join()}>{r.map((c,i)=><td key={i}>{i===3?<span className="badge badge-yellow">{c}</span>:c}</td>)}<td><button className="action-menu"><MoreHorizontal size={17}/></button></td></tr>)}</tbody></table></div></section></>}
 {pathname==="/admin/members"&&<><Header title="Members" desc="Search players and manage membership terms, benefits and allowance balances." action={<button className="btn btn-secondary"><Search size={16}/> Search members</button>}/><section className="card card-pad"><MemberTable onManage={setManaged}/></section></>}
 {pathname==="/admin/wallet"&&<><Header title="Wallet Adjustments" desc="Add or remove Club Credits with a required administrative reason." action={<button className="btn btn-primary"><Plus size={16}/> New adjustment</button>}/><section className="card card-pad"><div className="table-wrap"><table className="admin-table"><thead><tr><th>Player</th><th>Date</th><th>Adjustment</th><th>Reason</th><th>Admin</th><th>Balance after</th></tr></thead><tbody>{[["Bernard Small","23 Aug 2026","+30 CC","Credit correction","Admin User","650 CC"],["Nadia Khan","21 Aug 2026","-20 CC","Duplicate top-up reversal","Admin User","910 CC"],["Liam Meyer","18 Aug 2026","+50 CC","Club promotion","Admin User","320 CC"]].map(r=><tr key={r.join()}>{r.map((c,i)=><td key={i}><span style={i===2?{fontWeight:850,color:c.startsWith('+')?'var(--teal)':'var(--danger)'}:{}}>{c}</span></td>)}</tr>)}</tbody></table></div></section></>}
 </main>{managed&&<div className="modal-backdrop" onMouseDown={()=>setManaged(null)}><section className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><div className="eyebrow">Manage membership</div><h2 style={{margin:0}}>{managed}</h2></div><button className="icon-button" onClick={()=>setManaged(null)}><X size={18}/></button></div><div className="modal-body"><div className="summary-grid"><label className="summary-item"><span>Membership plan</span><select className="filter-control" style={{width:"100%"}}><option>Member</option><option>Pickle Pro</option><option>Play & Go</option></select></label><label className="summary-item"><span>Activation date</span><input type="date" defaultValue="2026-08-10" className="filter-control" style={{width:"100%"}}/></label><label className="summary-item"><span>Payment amount</span><input defaultValue="750" className="filter-control" style={{width:"100%"}}/></label><div className="summary-item"><span>Payment method</span><strong>Card Machine</strong></div></div><label style={{display:"block",marginTop:14}}><span style={{display:"block",fontSize:11,color:"var(--muted)",fontWeight:750,marginBottom:6}}>Admin note</span><input className="filter-control" style={{width:"100%"}} placeholder="Optional reference or note"/></label><div className="price-box"><div className="price-row"><span>Calculated end date</span><strong>10 September 2026</strong></div><div className="price-row"><span>Free hours this period</span><strong>1 hour</strong></div></div></div><div className="modal-footer"><button className="btn btn-secondary" onClick={()=>setManaged(null)}>Close</button><button className="btn btn-primary" onClick={()=>setManaged(null)}>Save membership</button></div></section></div>}</div>
}
